#port
server:  port: 8090

#app name
spring:  application:    name: eureka-discovery-service

eureka:  client:    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

